Fixed Built Doc Files from zipping.
pyansys/pyfluent pull request #1273
Opened 2023-01-16 19:57 UTC by alikasim72

As the upload-artifact action already zips the file, the prior manual compression in the file is unnecessary and leads to "double compression" which is only uncompressed once during deployment stage. Hence, the lines of manual compression were omitted to fix this issue.

2023-01-16 20:52 UTC, mkundu1 commented
Uploading the doc artifact now takes [13 min](https://github.com/pyansys/pyfluent/actions/runs/3933547412/jobs/6727373010#step:15:20) instead of [35 sec](https://github.com/pyansys/pyfluent/actions/runs/3906690005/jobs/6675139815#step:16:20). Not zipping the doc artifact fixes the deployment, so we can zip it when we don't need to deploy.

2023-01-17 06:51 UTC, jorgepiloto commented
Pinging here @MaxJPRey. I know PyAEDT run into a similar issue at some point but after checking their CI/CD pipelines it looks like they are no longer compressing the artifact.

I guess we could add an input parameter in pyansys actions to unzip the different artifacts.

2023-01-17 19:03 UTC, MaxJPRey commented
> Pinging here @MaxJPRey. I know PyAEDT run into a similar issue at some point but after checking their CI/CD pipelines it looks like they are no longer compressing the artifact.
> 
> I guess we could add an input parameter in pyansys actions to unzip the different artifacts.

Agreed to expose the argument to unzip the content.

2023-01-18 05:55 UTC, jorgepiloto commented
I just opened https://github.com/pyansys/actions/issues/143 to implement this.

2023-01-18 08:41 UTC, jorgepiloto commented
Now that the decompress logic got added in the pyansys/actions, could you use the `decompress_artifact` input variable, @alikasim72?

2023-01-18 19:27 UTC, alikasim72 commented
Updated the code by adding back the compression code lines and setting the `decompress_artifact` to True.

2023-01-19 01:46 UTC, mkundu1 approved these changes

2023-01-19 03:24 UTC, dnwillia-work commented on .github/workflows/ci.yml
> +          path: doc.zip
maybe remove whitespace?

2023-01-19 06:20 UTC, jorgepiloto requested changes

2023-01-19 06:20 UTC, jorgepiloto commented on .github/workflows/ci.yml
> +          path: doc.zip
```suggestion
          path: doc.zip
```

2023-01-19 06:21 UTC, jorgepiloto approved these changes

2023-01-19 11:24 UTC, merged